adminbusiness/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('dashboard', views.businessDashboard, name="business-dash"),

    # for service
    path('show-service', views.getService, name="get-service-dash"),
    path('new-service', views.postService, name="post-service-dash"),
    path('update-service/<int:service_id>',
         views.updateService, name="update-service-dash"),
    path('delete-service/<int:service_id>',
         views.deleteService, name="delete-service-dash"),

    # for Worker
    path('show-workers', views.getWorker, name="get-worker-dash"),
    path('create-worker', views.Worker_registration, name="post-worker-dash"),
    path('update-worker/<int:Worker_id>',
         views.updateWorker, name="update-worker-dash"),
    path('delete-worker/<int:Worker_id>',
         views.deleteWorker, name="delete-worker-dash"),

    # for profile
    # path('show-profile', views.getProfile, name="get-profile-dash"),
    path('edit-business', views.editBusiness, name="edit-business-dash"),
    path('edit-business-profile', views.editBusinessProfile,
         name="edit-business-profile-dash"),
    path('update-profile/<int:profile_id>',
         views.updateProfile, name="update-profile-dash"),

    path('change-password', views.change_password, name='change-password-dash'),

    # For Hiring
    path('hirings/', views.BusinessHiringListView.as_view(),
         name='business-hiring-list'),
    path('hirings/approve/<int:id>', views.approve_business_hiring,
         name='approve-business-hiring'),
    path('hirings/complete/<int:id>', views.complete_business_hiring,
         name='complete-business-hiring'),
    path('hirings/reject/<int:id>', views.reject_business_hiring,
         name='reject-business-hiring'),

    # for notification
    path('api/notification/<int:notification_pk>',
         views.HireNotificationView.as_view(), name='business-hire-notification-api'),
    path('notifications/', views.AllNotificationPageView.as_view(),
         name="business-all-notification-page"),

     # for gallery
    path('show-gallery', views.getGallery, name="get-gallery-dash"),
    path('add-gallery', views.postGallery, name="post-gallery-dash"),
    path('update-gallery/<int:gallery_id>',
         views.updateGallery, name="update-gallery-dash"),
    path('delete-gallery/<int:gallery_id>',
         views.deleteService, name="delete-gallery-dash"),

]

app_name = 'adminbusiness'

hiring/urls.py
# External Import
from hiring.views import CreateHireView
from django.urls import path

urlpatterns = [
    path('hire/', CreateHireView.as_view(), name='hire-business-service')
]

app_name = 'hiring'

servicefind/urls.py
# External Import
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('accounts.urls')),
    path('', include('homepage.urls')),
    # path('', include('Customer.urls')),
    path('myadmin/', include('admindashboard.urls')),
    path('mybusiness/', include('adminbusiness.urls')),
    path('', include('customer.urls')),
    path('', include('accounts.urls')),
    path('', include('business.urls')),
    path('', include('homepage.urls')),
    path('services/', include('service.urls')),
    path('', include('hiring.urls')),
    path('worker/', include('worker.urls')),

]

# Static & Media Management Files For Debug Mode Only.
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

notification/models.py
from django.db import models
from business.models import *
from customer.models import *
from django.utils import timezone
from business.models import Business_Service

from django.contrib.auth import get_user_model

User = get_user_model()

class Notification(models.Model):
    to_user = models.ForeignKey(
        User, related_name='notification_to', on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(
        User, related_name='notification_from', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255, null=True)
    business_service = models.ForeignKey(
        Business_Service, on_delete=models.CASCADE, null=True, blank=True)
    message = models.CharField(max_length=255, null=True)
    has_seen = models.BooleanField(default=False, null=True)
    datetime = models.DateTimeField(default=timezone.now)

adminbusiness/forms.py
from django.db.models import fields
from django.forms import ModelForm
from business.models import *
from gallery.models import *
from worker.models import *
from customer.models import *
from service.models import *
from hiring.models import *
from review.models import *
from notification.models import *
from django import forms
from datetime import date

class ServicesForm(ModelForm):
    class Meta:
        model = Services
        fields = '__all__'


class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = "__all__"
        exclude = ['user', 'slug', ]


class EditBusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ["name", "logo", "cover_picture", "is_solo"]


class BusinessProfileForm(ModelForm):
    class Meta:
        model = Business_Profile
        fields = "__all__"
        widgets = {'established': forms.widgets.DateInput(attrs={'type': 'date', 'max': date.today()})}
        exclude = ['business', 'experience_year',
                   'happy_customers', 'service_provided', 'awards_won']

class BusinessProfileForm1(ModelForm):
    class Meta:
        model = Business
        fields = ['contact_email']


class GalleryForm(ModelForm):
    class Meta:
        model = Gallery
        fields = "__all__"


class WorkerForm(ModelForm):
    class Meta:
        model = Worker
        fields = '__all__'


class BusinessServicesForm(ModelForm):
    class Meta:
        model = Business_Service
        fields = '__all__'
        exclude = ['business']


class BusinessServicesForm1(ModelForm):
    class Meta:
        model = Business_Service
        fields = '__all__'
        exclude = ['business', 'service']


class BusinessWorkerForm(ModelForm):
    class Meta:
        model = Worker
        fields = '__all__'
        exclude = ['business', 'user', 'slug']


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"


class HiringForm(ModelForm):
    class Meta:
        model = Services
        fields = '__all__'


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = "__all__"


class NotificationForm(ModelForm):
    class Meta:
        model = Notification
        fields = '__all__'


class WorkerCreationForm(ModelForm):
    Worker_name = forms.CharField(max_length=255, required=False)

    class Meta:
        model = User
        fields = ('username', 'email','Worker_name')

class BusinessGalleryForm(ModelForm):
    class Meta:
        model = Gallery
        fields = '__all__'
        exclude= ['business']

adminbusiness/views.py
from django.contrib import messages
from django.urls.base import reverse_lazy
import random
import string
import datetime
from .forms import *
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import (
    ListView,
    DeleteView,
    View
)

from django.contrib.auth.decorators import login_required
from accounts.auth import *

from accounts import utils
from django.contrib.sites.shortcuts import get_current_site

# internal input
from business.models import Business
from django.shortcuts import redirect, render
from business.models import *
from gallery.models import *
from worker.models import *
from customer.models import *
from service.models import *
from hiring.models import *
from review.models import *
from notification.models import *

from .filters import *

# Create your views here.


@login_required
@business_only
def businessDashboard(request):
    user = request.user
    business = Business.objects.get(user=user)
    gallery = Gallery.objects.all()
    business_service = Business_Service.objects.filter(
        business=user.business)
    business_service_count = Business_Service.objects.filter(
        business=user.business).count()
    worker = Worker.objects.filter(business=user.business)
    worker_count = Worker.objects.filter(business=user.business).count()
    customer = Hiring.objects.filter(business_service__business=user.business)
    customer_count = Hiring.objects.filter(
        business_service__business=user.business).count()
    hiring = Hiring.objects.all()
    hiring_count = Hiring.objects.filter(
        business_service__business=user.business).count()
    review = Review.objects.filter(business=user.business)
    review_count = Review.objects.filter(business=user.business).count()

    context = {
        'business': business,
        'gallery': gallery,
        'business_service': business_service,
        'business_service_count': business_service_count,
        'worker': worker,
        'worker_count': worker_count,
        'customer': customer,
        'customer_count': customer_count,
        'hiring': hiring,
        'hiring_count': hiring_count,
        'review': review,
        'review_count': review_count,
    }

    return render(request, 'adminbusiness/base/dashboard.html', context)


@login_required
@business_only
def getService(request):
    businessService = Business_Service.objects.filter(
        business=request.user.business)
    service_filter = ServicesFilter(request.GET, queryset=businessService)
    # service_filter1 =  service_filter.bu
    service_final = service_filter.qs

    context = {
        'businessService': service_final,
        'service_filter': service_filter,
    }
    return render(request, 'adminbusiness/base/show-service.html', context)


@login_required
@business_only
def postService(request):
    if request.method == 'POST':

        form = BusinessServicesForm(request.POST, request.FILES)
        if form.is_valid():
            businessService = Business_Service.objects.filter(
                business=request.user.business)

            obj = form.save(commit=False)
            already_exist = True
            for ser in businessService:
                if ser.service == obj.service:
                    already_exist = False
            if already_exist:
                obj.business = request.user.business
                obj.save()
                messages.add_message(
                    request, messages.SUCCESS, 'Service Added Successfully')
            else:
                messages.add_message(request, messages.ERROR,
                                     'The Service Already Exist')
            return redirect('adminbusiness:get-service-dash')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error adding service')
            return render(request, 'adminbusiness/base/post-service.html')
    else:
        form = BusinessServicesForm()

    context = {
        'form': form
    }

    return render(request, 'adminbusiness/base/post-service.html', context)


@login_required
@business_only
def updateService(request, service_id):
    instance = Business_Service.objects.get(id=service_id)
    if request.method == "POST":
        form = BusinessServicesForm1(
            request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('adminbusiness:get-service-dash')
    context = {
        'form': BusinessServicesForm1(instance=instance),
        'service': instance
    }
    return render(request, 'adminbusiness/base/update-service.html', context)


@login_required
@business_only
def deleteService(request, service_id):
    service = Business_Service.objects.get(id=service_id)
    service.delete()
    return redirect('adminbusiness:get-service-dash')


# for profile
@login_required
@business_only
def getProfile(request):
    profile = Business_Profile.objects.filter(business=request.user.business)

    context = {
        'profile': profile
    }
    return render(request, 'adminbusiness/base/show-profile.html', context)


@login_required
@business_only
def editBusiness(request):
    if request.method == 'POST':
        form = EditBusinessForm(
            request.POST, request.FILES, instance=request.user.business)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Business Edited Successfully')
            return redirect('adminbusiness:edit-business-dash')

        else:
            messages.add_message(request, messages.ERROR,
                                 'Error Editing Business')
    else:
        form = EditBusinessForm(
            instance=request.user.business)
    context = {
        'form': form
    }
    return render(request, 'adminbusiness/base/edit-business.html', context)


@login_required
@business_only
def editBusinessProfile(request):
    if request.method == 'POST':
        form = BusinessProfileForm(
            request.POST, request.FILES, instance=request.user.business.business_profile)
        form1 = BusinessProfileForm1(
            request.POST, request.FILES, instance=request.user.business)
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Business Profile Edited Successfully')
            return redirect('adminbusiness:edit-business-profile-dash')

        else:
            messages.add_message(request, messages.ERROR,
                                 'Error adding Business Profile')
    else:
        form = BusinessProfileForm(
            instance=request.user.business.business_profile)
        form1 = BusinessProfileForm1(
            instance=request.user.business)
    context = {
        'form': form,
        'form1': form1
    }
    return render(request, 'adminbusiness/base/post-profile.html', context)


@login_required
@business_only
def updateProfile(request, profile_id):
    instance = Business_Profile.objects.get(id=profile_id)
    if request.method == "POST":
        form = BusinessProfileForm(
            request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('adminbusiness:edit-business-profile-dash')
    context = {
        'form': BusinessProfileForm(instance=instance),
    }
    return render(request, 'adminbusiness/base/update-profile.html', context)


@login_required
@business_only
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('adminbusiness:business-dash')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'adminbusiness/base/change-password.html', {
        'form': form
    })


@login_required
@business_only
def getWorker(request):
    businessWorker = Worker.objects.filter(business=request.user.business)
    worker_filter = WorkerFilter(request.GET, queryset=businessWorker)
    worker_final = worker_filter.qs

    context = {
        'businessWorker': worker_final,
        'worker_filter': worker_filter,
    }
    return render(request, 'adminbusiness/base/show-worker.html', context)


# @login_required
# @business_only
# def postWorker(request):
#     if request.method == 'POST':

#         form = BusinessWorkerForm(request.POST, request.FILES)
#         if form.is_valid():
#             businessWorker = Worker.objects.filter(
#                 business=request.user.business)

#             obj = form.save(commit=False)
#             obj.business = request.user.business
#             obj.save()
#             messages.add_message(request, messages.SUCCESS,
#                                  'Service Added Successfully')
#             return redirect('getWorkerDash')
#         else:
#             messages.add_message(request, messages.ERROR,
#                                  'Error adding service')
#             return render(request, 'adminbusiness/base/post-worker.html')
#     else:
#         form = BusinessWorkerForm()

#     context = {
#         'form': form
#     }

#     return render(request, 'adminbusiness/base/post-worker.html', context)


@login_required
@business_only
def updateWorker(request, Worker_id):
    instance = Worker.objects.get(id=Worker_id)
    if request.method == "POST":
        form = BusinessWorkerForm(

adminbusiness/templates/adminbusiness/base/dashboard.html
{% extends 'adminbusiness/main/business-layout.html' %}
{% load static %}
{% block title %}
    Business Dashboard
{% endblock %}
{% block additional_head %}

<style>
   .container{
       margin-top: 6rem;
   }
   .card{
    background-color: #093B60;
   }
    

</style>
{% endblock %}

{% block main_content %} 

<!-- total service -->
<div class="container">
<div class="row">
    <!-- total service -->
      <div class="col-xl-3 col-sm-6 col-12 mb-4">
        <div class="card">
          <div class="card-body">
            <div class="d-flex justify-content-between px-md-1">
              <div>
                <h3 class="text-light">{{business_service_count}}</h3>
                <p class="mb-0 text-light">Total Services</p>
              </div>
              <div class="align-self-center"> 
                <a href="{% url 'adminbusiness:post-service-dash' %}"><i class="fa fa-wrench  text-light fa-3x"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    

    <!-- total customer -->
    <div class="col-xl-3 col-sm-6 col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between px-md-1">
            <div>
              <h3 class="text-light">{{customer_count}}</h3>
              <p class="mb-0 text-light">Total customer</p>
            </div>
            <div class="align-self-center">
              <i class="fa fa-users text-light fa-3x"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- hire request -->
    <div class="col-xl-3 col-sm-6 col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between px-md-1">
            <div>
              <h3 class="text-light">{{hiring_count}}</h3>
              <p class="mb-0 text-light">Hire Request</p>
            </div>
            <div class="align-self-center">
              <i class="fas fa-user-friends text-light fa-3x"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- total worker -->
    <div class="col-xl-3 col-sm-6 col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between px-md-1">
            <div>
              <h3 class="text-light">{{worker_count}}</h3>
              <p class="mb-0 text-light">Total Worker</p>
            </div>
            <div class="align-self-center">
              <i class="fas fa-hard-hat text-light fa-3x"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

<!-- for review -->
    <div class="col-xl-3 col-sm-6 col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between px-md-1">
            <div>
              <h3 class="text-light">{{review_count}}</h3>
              <p class="mb-0 text-light">Total Review</p>
            </div>
            <div class="align-self-center">
              <i class="fas fa-pencil-alt text-light fa-3x"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

{% block additional_body %}

{% endblock %}

adminbusiness/templates/adminbusiness/base/notification.html
{% load bootstrap %}
<!-- Notification dropdown -->
<li class="nav-item dropdown me-3 mt-2">

    <a
       class="nav-link me-3  me-lg-0 dropdown-toggle hidden-arrow"
       href="#"
       id="navbarDropdownMenuLink"
       role="button"
       data-mdb-toggle="dropdown"
       aria-expanded="false"
       >
      <i class="fas fa-bell"></i>
      <span class="badge rounded-pill badge-notification bg-danger"
            >{{notifications.count}}</span
        >
    </a>
    <ul
        class="dropdown-menu dropdown-menu-end "
        aria-labelledby="navbarDropdownMenuLink"
        
        >
    {% for noti in limit_notifications %}
    
      <li><a class="dropdown-item" href="{% url 'adminbusiness:business-hire-notification-api' noti.id %}">{{noti.message}}</a></li>
    {% endfor %}
    <span style=" margin-left:1.5rem; ">No new notification</span>
    <a class="text-center" style="margin-top: 12rem;" href="{% url 'adminbusiness:business-all-notification-page' %}"><p>View All</p></a>
    </ul>
    
  </li>

adminbusiness/templates/adminbusiness/base/show-gallery.html
{% extends 'adminbusiness/main/business-layout.html' %}
{% load static %}
{% block title %}
View Service
{% endblock %}
{% block additional_head %}
<link href="{% static 'css/business-dashboard.css' %}" rel="stylesheet">
<style>
    .container {
        margin-top: 6rem;
    }
    .text-center{
        color: #093B60
    }
    .btn-primary{
        background-color: #093B60;
    }

    .btn-primary:hover{
        background-color: #062c49;
    }
    .btn-light{
        background-color: #e1e1e1;
    }
</style>
{% endblock %}

{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 offset">
            <h1 class="text-center"> Gallery </h1>
            {% comment %} Show Messages {% endcomment %}
            {% for message in messages %}
            <div class="alert {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-warning{% else %}alert-secondary{% endif %} alert-dismissible fade show"
                role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            {% endfor %}

            <div class="card py-2 px-2 table-responsive">
                <a class="btn btn-primary btn-bg ml-auto mb-2" style="width: 100%"
                    href="{% url 'adminbusiness:post-gallery-dash' %}">Add New Gallery</a>

                <table class="table table-responsive table-white">
                    <tr class="btn-light">
                        <th>#</th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    {% for g in businessGallery %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.title }}</td>
                        <td><img src="{{ g.picture.url }}" alt="" width="50" height="50"></td>
                        <td>{{ g.description }}</td>

                        <td><a href="update-gallery/{{ g.id }}" class="btn btn-primary btn-sm">Edit</a>&nbsp;

                            <a href="delete-gallery/{{ g.id }}" class="btn btn-danger btn-sm"
                                onclick="return confirm('Are you sure want to delete this file?')">
                                Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block additional_body %}

{% endblock %}

adminbusiness/templates/adminbusiness/base/show-service.html
{% extends 'adminbusiness/main/business-layout.html' %}
{% load static %}
{% block title %}
View Service
{% endblock %}
{% block additional_head %}
<link href="{% static 'css/business-dashboard.css' %}" rel="stylesheet">
<style>
    .container {
        margin-top: 6rem;
    }
    
    .text-center{
        color: #093B60
    }
    .btn-primary{
        background-color: #093B60;
    }
    .btn-primary:hover{
        background-color: #072b47;
    }
    button{
        height: 2rem;
    }

    .add-btn{
        height: 2rem;
    }

    .btn-light{
        background-color: #e1e1e1;
    }

</style>
{% endblock %}

{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 offset">
            <h1 class="text-center"> Service </h1>
            {% comment %} Show Messages {% endcomment %}
            {% for message in messages %}
            <div class="alert {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-warning{% else %}alert-secondary{% endif %} alert-dismissible fade show"
                role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            {% endfor %}
            <div class="card py-2 px-2 table-responsive">

                <div class="card card-body" style="display: inline;">
                    <form class="form-label" method="get">
                        {{service_filter.form.service_name}}
                        <button class="btn btn-primary btn-sm" type="sumbit" data-inline="true">Search</button>
                    </form>
             
                </div>
                <a class="btn btn-primary btn-bg ml-auto mb-2" style="width: 100%"
                href="{% url 'adminbusiness:post-service-dash' %}">Add New Service</a>

              

                <table class="table table-responsive table-white">
                    <tr class="btn-light">
                        <th>#</th>
                        <th>Service Name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    {% for s in businessService %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ s.service }}</td>
                        <td>{{ s.description }}</td>

                        <td><a href="{% url 'adminbusiness:update-service-dash' s.id %}"
                                class="btn btn-primary btn-sm">Edit</a>&nbsp;

                            <a href="{% url 'adminbusiness:delete-service-dash' s.id %}" class="btn btn-danger btn-sm"
                                onclick="return confirm('Are you sure want to delete this file?')">
                                Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block additional_body %}

{% endblock %}

adminbusiness/templates/adminbusiness/base/show-worker.html
{% extends 'adminbusiness/main/business-layout.html' %}
{% load static %}
{% block title %}
    View Worker
{% endblock %}
{% block additional_head %}
<link href="{% static 'css/business-dashboard.css' %}" rel="stylesheet">
<style>
    .container{
        margin-top: 6rem;
    }

    .text-center{
        color: #093B60
    }

    .btn-primary{
        background-color: #093B60;
    }

    .btn-primary:hover{
        background-color: #062c49;
    }
    .btn-light{
        background-color: #e1e1e1;
    }

    button{
        height: 2rem;
    }

    .add-btn{
        height: 2rem;
    }

</style>
{% endblock %}

{% block main_content %} 
<div class="container">
    <div class="row">
        <div class="col-md-12 offset">
            <h1 class="text-center"> Worker </h1>
            <div class="card py-2 px-2 table-responsive">
                <div class="card card-body"  style="display: inline;">
                    <form class="form-label" method="get">
                        {{worker_filter.form.name}}
                        <button class="btn btn-primary btn-sm" type="sumbit">Search</button>
                    </form>
                </div>
                <a class="btn btn-primary btn-bg ml-auto mb-2" style="width: 100%"
                   href="{% url 'adminbusiness:post-worker-dash' %}">Add New Worker</a>
                   
                <table class="table table-responsive table-white" >
                    <tr class="btn-light">
                        <th>#</th>
                        <th>Worker Name</th>
                        <th>Picture</th>
                        <th>Status</th>
                        <th>Phone</th>
                        <th>Action</th>
                    </tr>
                    {% for w in businessWorker %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ w.name }}</td>
                        <td>{{ w.picture }}</td>
                        <td>{{ w.is_active }}</td>
                        <td>{{ w.phone }}</td>

                       <td><a href="{% url 'adminbusiness:update-worker-dash' w.id %}"
                               class="btn btn-primary btn-sm">Edit</a>&nbsp;
                    
                            <a href="{% url 'adminbusiness:delete-worker-dash' w.id %}"
                               class="btn btn-danger btn-sm"
                               onclick="return confirm('Are you sure want to delete this file?')">
                                Delete</a></td> 
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block additional_body %}

{% endblock %}