business/urls.py
# External Import
from django.urls import path
from .import views
# Internal Import
from .views import(
    BusinessListPageView,
    BusinessReportingView,
)


urlpatterns = [
    path('business/', BusinessListPageView.as_view(), name='business-list-page'),
    path('business-profile/<str:slug>/',
         views.BusinessProfileView.as_view(), name='business-profile'),
    path('api/report-business/', BusinessReportingView.as_view(),
         name='user-report-business')
]

app_name = 'business'

hiring/urls.py
# External Import
from hiring.views import CreateHireView
from django.urls import path

urlpatterns = [
    path('hire/', CreateHireView.as_view(), name='hire-business-service')
]

app_name = 'hiring'

servicefind/urls.py
# External Import
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('accounts.urls')),
    path('', include('homepage.urls')),
    # path('', include('Customer.urls')),
    path('myadmin/', include('admindashboard.urls')),
    path('mybusiness/', include('adminbusiness.urls')),
    path('', include('customer.urls')),
    path('', include('accounts.urls')),
    path('', include('business.urls')),
    path('', include('homepage.urls')),
    path('services/', include('service.urls')),
    path('', include('hiring.urls')),
    path('worker/', include('worker.urls')),

]

# Static & Media Management Files For Debug Mode Only.
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

business/models.py
# External Import
from django.db.models.fields.files import ImageField
from django.db.models.signals import pre_save, post_save
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q
import re

# Internal Import
from service.models import *
from .utils import unique_slug_generator
from review.models import Review
User = get_user_model()


def normalize_query(query_string, findterms=re.compile(r'"([^"]+)"|(\S+)').findall, normspace=re.compile(r'\s{2,}').sub):
    return [normspace('', (t[0] or t[1]).strip()) for t in findterms(query_string)]


PROVINCE_CHOICES = (
    ('Province 1', 'Province 1'),
    ('Province 2', 'Province 2'),
    ('Bagmati', 'Bagmati'),
    ('Gandaki', 'Gandaki'),
    ('Lumbini', 'Lumbini'),
    ('Karnali', 'Karnali'),
    ('Sudhurpachhim', 'Sudhurpachhim'),
)


class BusinessQuerySet(models.query.QuerySet):

    def admin(self):
        return self.all()

    def active(self):
        return self.filter(is_active=True).distinct()

    def search(self, query_string):

        query = None
        terms = normalize_query(query_string)
        search_fields = ['name', 'slug', 'business_profile__intro', 'business_profile__founder', 'business_profile__moto',
                         'business_service__service__name', 'business_service__service__servicetag__title']
        for term in terms:
            or_query = None  # Query to search for a given term in each field
            for field_name in search_fields:
                q = Q(**{"%s__icontains" % field_name: term})
                if or_query is None:
                    or_query = q
                else:
                    or_query = or_query | q
            if query is None:
                query = or_query
            else:
                query = query | or_query
        return self.filter(query)


class BusinessManager(models.Manager):

    def get_queryset(self):
        return BusinessQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def search(self, query_string):
        return self.get_queryset().search(query_string)

    def foradmin(self):
        return self.get_queryset().admin()


class Business(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    name = models.CharField(max_length=50)
    logo = models.ImageField(
        blank=True, null=True, upload_to="business/logo/", default="business/logo/default/default.png")
    cover_picture = models.ImageField(
        blank=True, null=True, upload_to="business/cover/", default="business/cover/default/default.jpg")
    slug = models.SlugField(unique=True, blank=True, null=True)
    district = models.CharField(max_length=100)
    province = models.CharField(
        max_length=100, choices=PROVINCE_CHOICES, null=True)
    is_solo = models.BooleanField(default=False)
    street_address = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=50)
    is_verified = models.BooleanField(default=False)
    contact_email = models.EmailField(max_length=50)

    objects = BusinessManager()

    def __str__(self):
        return self.name + " | " + self.user.username

    def get_avg_rating(self):
        reviews = Review.objects.filter(business=self)
        count = len(reviews)
        if count == 0:
            return 0
        sum = 0
        for rvw in reviews:
            sum += rvw.rating
        avg = sum/count
        return round(avg, 1)

    def total_reviews(self):
        reviews = Review.objects.filter(business=self)
        count = len(reviews)
        return count

# This is done to create unique slug for the business


def post_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.slug = unique_slug_generator(instance)


# Connecting pre_save_receiver function and sender Post
pre_save.connect(post_pre_save_receiver, sender=Business)


class Business_Service(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    description = models.TextField(max_length=500, blank=True, null=True)

    def __str__(self):
        name = str(self.business)+"-->"+str(self.service)
        return name


Language_CHOICES = (
    ('Nepali', 'Nepali'),
    ('English', 'English'),
)


class Business_Profile(models.Model):
    business = models.OneToOneField(Business, on_delete=models.CASCADE)
    # Business_Service=models.OneToManyField(Business_Service)
    intro = models.TextField(null=True)
    established = models.DateField(null=True)
    founder = models.CharField(max_length=30, null=True)
    moto = models.CharField(max_length=100, null=True)
    language = models.CharField(
        choices=Language_CHOICES, max_length=100, null=True)
    experience_year = models.IntegerField(null=True)
    service_provided = models.IntegerField(null=True)
    happy_customers = models.IntegerField(null=True)
    awards_won = models.IntegerField(null=True)


def create_business_profile(sender, instance, created, **kwargs):
    if created:
        Business_Profile.objects.create(business=instance)


# This Creates the business profile once business is created
post_save.connect(create_business_profile, sender=Business)

accounts/forms.py
# External Improt
from customer.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms


# Internal Import
from customer.models import Customer, PROVINCE_CHOICES
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomerRegistrationForm(UserCreationForm):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    province = forms.ChoiceField(choices=PROVINCE_CHOICES)
    city = forms.CharField(max_length=200, required=True)
    street_address = forms.CharField(max_length=200, required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        user = User.objects.filter(email=email)
        if user:
            self.add_error('email', 'User with this Email already exists.')


class CustomerLoginForm(AuthenticationForm):

    class Meta:
        model = User


class BusinessRegistrationForm(UserCreationForm):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    province = forms.ChoiceField(choices=PROVINCE_CHOICES)
    district = forms.CharField(max_length=200, required=True)
    city = forms.CharField(max_length=200, required=True)
    street_address = forms.CharField(max_length=200, required=True)
    is_solo = forms.BooleanField(required=False)

    class Meta(UserCreationForm.Meta):
        model = User

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        user = User.objects.filter(email=email)
        if user:
            self.add_error('email', 'User with this Email already exists.')


class BusinessLoginForm(AuthenticationForm):

    class Meta:
        model = User

business/forms.py
# External Import
from django import forms

# Internal Import
from review.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'
        exclude = ['customer', 'business', 'is_active']

business/views.py
# External Import
from gallery.models import Gallery
from customer.models import Customer
import business
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    FormView,
    View,
)
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseForbidden, request
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib import messages


# Internal Import
from worker.models import Worker
from bookmark.models import Bookmark
from business.models import Business
from review.models import Review
from hiring.models import Hiring
from worker.models import *
from .forms import ReviewForm
from reportuser.models import ReportUser


class BusinessListPageView(UserPassesTestMixin, ListView):
    template_name = "business/business-list-page.html"
    paginate_by = 10

    # Check if the user can access this page
    # Declare permission who can access this page
    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user.is_customer
        return True

    # Redirect user to who doesn't have permission to access this page
    def handle_no_permission(self):
        if self.request.user.is_business:
            return redirect('adminbusiness:business-dash')
        elif self.request.user.is_staff:
            return redirect('admindashboard:my-admin-dashboard')
        elif self.request.user.is_worker:
            return redirect('worker:worker-dashboard')
        return redirect('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer_bookmarks_business = []
        if self.request.user.is_authenticated and self.request.user.is_customer:
            customer_bookmarks = Bookmark.objects.filter(
                customer=self.request.user.customer).values_list('business', flat=True)
            customer_bookmarks_business = [Business.objects.get(id=id) for id in
                                           customer_bookmarks]
        query = self.request.GET.get('q')
        if query is not None:
            context["query"] = query

        context["customer_bookmarks_business"] = customer_bookmarks_business
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)
        if query is not None and query != '':
            return Business.objects.search(query).active().distinct()
        return Business.objects.all()


class BusinessProfileView(UserPassesTestMixin, FormMixin, DetailView):
    queryset = Business.objects.all()
    template_name = "business/business-profile.html"
    slug_url_kwarg = 'slug'
    form_class = ReviewForm

    # Check if the user can access this page
    # Declare permission who can access this page
    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user.is_customer
        else:
            return True
        return False

    # Redirect user to who doesn't have permission to access this page
    def handle_no_permission(self):
        if self.request.user.is_business:
            return redirect('adminbusiness:business-dash')
        elif self.request.user.is_staff:
            return redirect('admindashboard:my-admin-dashboard')
        elif self.request.user.is_worker:
            return redirect('worker:worker-dashboard')
        return redirect('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        worker = Worker.objects.filter(business__slug=slug)
        context["Worker"] = worker
        review = Review.objects.filter(business__slug=slug)
        context["review"] = review
        business_gallery = Gallery.objects.filter(business__slug=slug)
        context["business_gallery"] = business_gallery
        no_of_hiring_completed = Hiring.objects.filter(
            business_service__business__slug=slug, status='CO').count()
        context["hiring_completed"] = no_of_hiring_completed
        current_user_business_review = None
        is_bookmarked = False
        if self.request.user.is_authenticated and self.request.user.is_customer:
            try:
                current_user_business_review = Review.objects.get(
                    customer=self.request.user.customer, business=self.object)
            except Review.DoesNotExist:
                current_user_business_review = None

            try:
                current_user_bookmarked = Bookmark.objects.get(
                    customer=self.request.user.customer, business=self.object)
            except Bookmark.DoesNotExist:
                current_user_bookmarked = None

            if current_user_bookmarked:
                is_bookmarked = True

            context["form"] = ReviewForm(instance=current_user_business_review)
        if current_user_business_review == None:
            context["customer_review_exist"] = False
        context["is_bookmarked"] = is_bookmarked

        customer_has_hired = False
        # Knowing if the user have hire this business or not
        if self.request.user.is_authenticated:
            user = User.objects.get(id=self.request.user.id)
            customer = user.customer
            current_customer_hiring = Hiring.objects.filter(
                business_service__business__slug=slug, customer=customer, status__in=('AC'))
            if current_customer_hiring:
                customer_has_hired = True
        context['customer_has_hired'] = customer_has_hired
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            try:
                user_business_review = Review.objects.get(
                    customer=request.user.customer, business=self.object)
                user_business_review.comment = form.cleaned_data.get('comment')
                user_business_review.rating = form.cleaned_data.get('rating')
                user_business_review.save()
            except Review.DoesNotExist:
                review = form.save(commit=False)
                review.business = self.object
                review.customer = self.request.user.customer
                review.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('business:business-profile', kwargs={'slug': self.object.slug})


class BusinessReportingView(UserPassesTestMixin, View):

    def test_func(self):
        if not self.request.user.is_authenticated and not self.request.user.is_staff:
            return False
        return True

    def post(self, request):
        business_slug = request.POST['business-slug']
        reported_text = request.POST['reported-text']

        # Get Business
        reported_user = Business.objects.get(slug=business_slug).user
        reported_by = request.user

        # Check whether user has reported earlier
        previous_report = ReportUser.objects.filter(
            suspicious_user=reported_user, reported_by=reported_by, status='PE')

        if previous_report:
            messages.warning(
                request, f'You have already reported this business. Our Team in working on your report. We will inform you soon. Sorry For Your Inconvenience 🙏')
        else:
            # Create Reporting
            ReportUser.objects.create(
                suspicious_user=reported_user, reported_by=reported_by, reported_message=reported_text)

            messages.success(
                request, f'You have successfully reported {reported_user.business.name}. We will check your report soon. Sorry For Your Inconvenience 🙏')

        return redirect(request.META.get('HTTP_REFERER', 'customer-home'))

business/templates/business/business-list-page.html
{% extends 'base/layout.html' %}
{% load static %}
{% load class_tag_filter %}
{% block additional_head %}
<link rel="stylesheet" href="{% static 'business/css/business-list-page.css' %}">
{% endblock %}
{% block main_content %}
    {% include 'business/snippets/business-advanced-search.html' %}
<div class="container pt-5 pb-5">
    <div class="d-flex justify-content-center row">
        {% if object_list %}
        {% for object in object_list  %}
        <div class="col-lg-10 col-md-12 m-1 mb-3">
            {% comment %} To make code easy to read {% endcomment %}
            {% include 'business/snippets/business-card.html' with obj=object customer_bookmarks=customer_bookmarks_business%}
        </div>
        {% endfor %}
        {% else %}
        <div class="container text-center mt-3">
            <div class="row">
                <div class="col-md-12">
                <img src="{% static 'img/websites/no_search_result_found.png' %}" width="200" height="200">
                    <div class="error-template">
                        <h5>No Business Found</h5>
                        <div class="error-details">
                            Sorry, no business found!
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if is_paginated %}
        <nav aria-label="Business Pagination" class="mt-4">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?q={{ request.GET.q }}&page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?q={{ request.GET.q }}&page={{page_obj.previous_page_number}}"
                        tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?q={{ request.GET.q }}&page={{num}}">{{num}}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?q={{ request.GET.q }}&page={{num}}">{{num}}</a></li>

                {% endif %}

                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?q={{ request.GET.q }}&page={{page_obj.next_page_number}}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?q={{ request.GET.q }}&page={{page_obj.paginator.num_pages}}"
                        aria-label="Last">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block additional_body %}
<script src="{% static 'business/js/decimal-to-star-display.js' %}"></script>
<script src="{% static 'customer/js/customer-bookmark-toggle.js' %}"></script>
<script src="{% static 'JS/customer_navbar.js' %}"></script>
{% endblock %}

business/templates/business/business-login.html
{% extends 'base/layout.html' %}
{% load static %}
{% load class_tag_filter %}
{% block title %}

{% encblock %}
{% block additional_head %}
<link rel="stylesheet" href="{% static 'customer/css/customer-login.css' %}">
{% endblock %}
{% block main_content %}
<div class="d-flex align-items-center min-vh-100 py-3 py-md-0">
  <div class="container">
    <div class="card login-card">
      <div class="row no-0">
        <div class="col-md-6 d-none d-lg-block text-center">
          <img src="{% static 'img/svg/people-search-svg.svg' %}" class="mt-5" height="500" width="500" alt="">
        </div>
        <div class="col-lg-6 col-md-8">
          <div class="card-body">
            <div class="brand-wrapper">
              <img
                src="https://imgr.search.brave.com/movByOJFG-Md0eCficaFtW-hLHIbaAlPplMeAEzRQqw/fit/474/225/no/1/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC51/TDBwT0NDNXhnZ0JI/eHFDamlTSXFnSGFI/YSZwaWQ9QXBp"
                alt="logo" class="logo">
            </div>
            <p class="login-card-description">Sign into your account</p>
            <form method="POST">
              {% csrf_token %}
              <div>
                <label for="id_username" class="sr-only">Email</label>
                {{form.username|addclass:'form-control'|addplaceholder:'Username or Email'}}

              </div>
              <div>
                <label for="id_password" class="sr-only">Password</label>
                {{form.password|addclass:'form-control'|addplaceholder:'Password'}}
              </div>

              {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
              {% endfor %}
              <button name="login" id="login" class="btn btn-block login-btn mb-4" value="Login">Login</button>
            </form>
            <a href="#!" class="forgot-password-link">Forgot password?</a>
            <p class="login-card-footer-text">Don't have an account? <a href="{% url 'business-registration' %}"
                class="text-reset">Register here</a></p>
            <nav class="login-card-footer-nav">
              <a href="#!">Terms of use.</a>
              <a href="#!">Privacy policy</a>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

business/templates/business/business-registration.html
{% extends 'base/layout.html' %}
{% load static %}
{% load class_tag_filter %}
{% block title %}
Business Registration
{% endblock %}
{% block additional_head %}
<link rel="stylesheet" href="{% static 'business/css/business-registration.css' %}">
{% endblock %}
{% block main_content %}
<div class="d-flex align-items-center min-vh-100 py-3 py-md-0">
  <div class="container">
    <div class="my-5 card login-card">
      <div class="row justify-content-center no-0">
        {% comment %} <div class="col-md-6 d-none d-lg-block text-center">
          <img src="{% static 'img/svg/people-search-svg.svg' %}" class="mt-5" height="500" width="500" alt="">
        </div> {% endcomment %}
        <div class="col-lg-10 col-md-12">
          <div class="card-body">
            <p class="login-card-description">Business Registration</p>
            <form method="POST">
              {% csrf_token %}
              <div>
                <div class="row">
                  <div class="col-md-6">
                    <label for="id_name" class="sr-only">Business Name</label>
                    {{form.name|addclass:'form-control'|addplaceholder:'Business Name'}}
                  </div>
                  <div class="col-md-6">
                    <label for="id_username" class="sr-only">Username</label>
                    {{form.username|addclass:'form-control'|addplaceholder:'Username'}}
                  </div>
                  {{ form.name.errors }}
                  {{ form.username.errors }}
                </div>
              </div>


              <div>
                <div class="row">
                  <div class="col-md-6">
                    <label for="id_email" class="sr-only">Email</label>
                    {{form.email|addclass:'form-control'|addplaceholder:'Email'}}
                  </div>
                  <div class="col-md-6">
                    <label for="id_phone" class="sr-only">Phone</label>
                    {{form.phone|addclass:'form-control'|addplaceholder:'Phone'}}
                  </div>
                  {{ form.email.errors }}
                  {{ form.phone.errors }}
                </div>
              </div>
              <div>
                <div class="row">
                  <div class="col-md-6">
                    <label for="id_province" class="sr-only">Province</label>
                    {{form.province|addclass:'form-control'|addplaceholder:'Province'}}
                  </div>
                  <div class="col-md-6">
                    <label for="id_district" class="sr-only">District</label>
                    {{form.district|addclass:'form-control'|addplaceholder:'District'}}
                  </div>
                  {{ form.district.errors }}
                  {{ form.province.errors }}
                </div>
              </div>

              <div>
                <div class="row">
                  <div class="col-md-6">
                    <label for="id_city" class="sr-only">City</label>
                    {{form.city|addclass:'form-control'|addplaceholder:'City'}}
                  </div>
                  <div class="col-md-6">
                    <label for="id_street_address" class="sr-only">Street Address</label>
                    {{form.street_address|addclass:'form-control'|addplaceholder:'Street Address'}}
                  </div>
                  {{ form.city.errors }}
                  {{ form.street_address.errors }}
                </div>
              </div>
              <div>
                <div class="row">
                  <div class="col-md-6">
                    <label for="id_password1" class="sr-only">Password</label>
                    {{form.password1|addclass:'form-control'|addplaceholder:'Password'}}
                  </div>
                  <div class="col-md-6">
                    <label for="id_password2" class="sr-only">Confirm Password</label>
                    {{form.password2|addclass:'form-control'|addplaceholder:'Confirm Password'}}
                  </div>
                  {{ form.password2.errors }}
                  {{ form.password1.errors }}
                </div>
              </div>
              <div class="mb-3">
                {{form.is_solo}}
                <label for="id_is_solo">I am working on my own</label>

              </div>

              {% for error in form.non_field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
              {% endfor %}
              <button name="login" id="login" class="btn btn-block login-btn mb-4" value="Register">Register</button>
            </form>
            <p class="login-card-footer-text " >or</p>

            <p class="login-card-footer-text"><a href="{% url 'customer-registration' %}"
                >Customer Registeration</a> </p>
                
            <p class="login-card-footer-text">Already have an account? <a href="{% url 'login' %}"
                class="text-reset">Login Here</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}