adminbusiness/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('dashboard', views.businessDashboard, name="business-dash"),

    # for service
    path('show-service', views.getService, name="get-service-dash"),
    path('new-service', views.postService, name="post-service-dash"),
    path('update-service/<int:service_id>',
         views.updateService, name="update-service-dash"),
    path('delete-service/<int:service_id>',
         views.deleteService, name="delete-service-dash"),

    # for Worker
    path('show-workers', views.getWorker, name="get-worker-dash"),
    path('create-worker', views.Worker_registration, name="post-worker-dash"),
    path('update-worker/<int:Worker_id>',
         views.updateWorker, name="update-worker-dash"),
    path('delete-worker/<int:Worker_id>',
         views.deleteWorker, name="delete-worker-dash"),

    # for profile
    # path('show-profile', views.getProfile, name="get-profile-dash"),
    path('edit-business', views.editBusiness, name="edit-business-dash"),
    path('edit-business-profile', views.editBusinessProfile,
         name="edit-business-profile-dash"),
    path('update-profile/<int:profile_id>',
         views.updateProfile, name="update-profile-dash"),

    path('change-password', views.change_password, name='change-password-dash'),

    # For Hiring
    path('hirings/', views.BusinessHiringListView.as_view(),
         name='business-hiring-list'),
    path('hirings/approve/<int:id>', views.approve_business_hiring,
         name='approve-business-hiring'),
    path('hirings/complete/<int:id>', views.complete_business_hiring,
         name='complete-business-hiring'),
    path('hirings/reject/<int:id>', views.reject_business_hiring,
         name='reject-business-hiring'),

    # for notification
    path('api/notification/<int:notification_pk>',
         views.HireNotificationView.as_view(), name='business-hire-notification-api'),
    path('notifications/', views.AllNotificationPageView.as_view(),
         name="business-all-notification-page"),

     # for gallery
    path('show-gallery', views.getGallery, name="get-gallery-dash"),
    path('add-gallery', views.postGallery, name="post-gallery-dash"),
    path('update-gallery/<int:gallery_id>',
         views.updateGallery, name="update-gallery-dash"),
    path('delete-gallery/<int:gallery_id>',
         views.deleteService, name="delete-gallery-dash"),

]

app_name = 'adminbusiness'

business/urls.py
# External Import
from django.urls import path
from .import views
# Internal Import
from .views import(
    BusinessListPageView,
    BusinessReportingView,
)


urlpatterns = [
    path('business/', BusinessListPageView.as_view(), name='business-list-page'),
    path('business-profile/<str:slug>/',
         views.BusinessProfileView.as_view(), name='business-profile'),
    path('api/report-business/', BusinessReportingView.as_view(),
         name='user-report-business')
]

app_name = 'business'

customer/urls.py
# External Import
from django.urls import path
from customer import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
#from .views import PasswordUpdateView


# Internal Import

urlpatterns = [
    path('profile/', views.profileupdate, name="customerprofile"),
    path('change-password/', views.change_password, name='change_password'),
    path('hirings/', views.CustomerHiringPageView.as_view(),
         name="customer-hiring-page"),
    path('hirings/delete/<pk>/', views.CustomerHiringDeleteView.as_view(),
         name='customer-hiring-delete-view'),
    path('bookmarks/', views.CustomerBusinessBookmarkListView.as_view(),
         name="customer-bookmark-page"),
    path('bookmarks/delete/<pk>/', views.CustomerBookmarkDeleteView.as_view(),
         name='customer-bookmark-delete-view'),
    path('bookmarks/<str:slug>/add-bookmark/',
         views.business_bookmark_toggle_for_customer, name='customer-bookmark-toggle'),
    path('api/notification/<int:notification_pk>',
         views.HireNotificationView.as_view(), name='hire-notification-api'),
    path('notifications/', views.AllNotificationPageView.as_view(),
         name="customer-all-notification-page"),
    path('notification/<int:id>/toggle-notification-status/',
         views.notification_seen_toggle_for_customer, name='customer-notification-toggle'),


]

# App Name
app_name = 'customer'

hiring/urls.py
# External Import
from hiring.views import CreateHireView
from django.urls import path

urlpatterns = [
    path('hire/', CreateHireView.as_view(), name='hire-business-service')
]

app_name = 'hiring'

servicefind/urls.py
# External Import
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('accounts.urls')),
    path('', include('homepage.urls')),
    # path('', include('Customer.urls')),
    path('myadmin/', include('admindashboard.urls')),
    path('mybusiness/', include('adminbusiness.urls')),
    path('', include('customer.urls')),
    path('', include('accounts.urls')),
    path('', include('business.urls')),
    path('', include('homepage.urls')),
    path('services/', include('service.urls')),
    path('', include('hiring.urls')),
    path('worker/', include('worker.urls')),

]

# Static & Media Management Files For Debug Mode Only.
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

worker/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('dashboard', views.workerDashboard, name="worker-dashboard"),
    path('worker-profile/<str:slug>',
         views.getProfile, name="worker-profile"),
    path('hirings', views.WorkerHiringListView.as_view(),
         name="worker-hiring-list"),
    path('hirings/complete/<int:id>', views.complete_worker_hiring,
         name='complete-worker-hiring'),
    path('change-password', views.change_password, name='change-password'),
    path('edit-profile', views.editWorker, name='edit-profile'),
]

app_name = 'worker'

templates/components/admin_nav_offcanvas.html
{% load static %}
<div class="container-fluid" id="Header">
    <nav class="navbar navbar-expand-sm">
        <h1>             
            <button class="btn m-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions" id="offcanvas_opener" onclick="hideOp()">
                <span class="fas fa-angle-double-right"></span>
            </button> 
        </h1>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" onclick="setH()">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="ms-auto" id="UDA">  
                <a class="fw-bold" href="" id="Username">{{request.user.username}}</a>
                <a class="btn lgo" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </nav>
</div>
<div class="offcanvas offcanvas-start sidebar_nav" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
    <div class="offcanvas-header ps-0 pe-2 py-0">
        <img class="img-fluid" src="{% static 'img/navbar/logo.png' %}" style="width: auto;" id="Logo" />  
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close" id="offcanvas-close" onclick="showOp()"></button>
    </div>
    <div class="offcanvas-body py-0">
        <nav class="navbar">
            <ul class="navbar-nav">
                <li><a href="{% url 'admindashboard:my-admin-dashboard' %}" class="nav-link {{dashboard}} px-2">
                    <span class="fas fa-tachometer-alt me-2"></span> <span>Dashboard</span>
                </a></li>
                <li class="dropdown-divider"></li>
                <li><a href="{% url 'admindashboard:service-list' %}" class="nav-link {{service}} px-2">
                    <span class="fas fa-tools me-2"></span> <span>Services</span>
                </a></li>
                <li class="dropdown-divider"></li>
                <li><a href="{% url 'admindashboard:show-all-business' %}" class="nav-link {{business}} px-2">
                    <span class="fas fa-user-tie me-2"></span> <span>Businesses</span>
                </a></li>
                <li class="dropdown-divider"></li>
                <li><a href="{% url 'admindashboard:my-admin-customer-list-view' %}" class="nav-link {{customer}} px-2">
                    <span class="fas fa-user-friends me-2"></span> <span>Customers</span>
                </a></li> 
                <li class="dropdown-divider"></li>
                <li><a href="{% url 'admindashboard:report-user' %}" class="nav-link {{report}} px-2">
                    <span class="fas fa-exclamation-circle me-2"></span> <span>Reports</span>
                </a></li> 
                <li class="dropdown-divider"></li>
            </ul>
        </nav>
    </div>
</div>

templates/components/customer-navbar.html
{% load custom_tags %}
{% load static %}
{% url 'home' as customer_home_page %}
{% url 'customer-services' as customer_service_page %}
{% url 'login' as login_page %}
{% url 'customer-registration' as customer_registration_page %}
{% url 'business-registration' as business_registration_page %}
{% url 'about-us' as about_us_page %}
{% url 'business:business-list-page' as business_list_page %}
<style>
#Username{
  font-size: 1rem;
  text-decoration: none;
  
}
#Username:hover{
  font-size: 1rem;
  text-decoration: none;
  color: #093B60;
  background-color: white
}
.lgo{
  color: red;
  
}
.lgo:hover{
  color: red;
  
}
</style>
<div class="container-fluid" id="Header">
  <nav class="navbar navbar-expand-sm navbar-default">
    <h1>
      <p class="img-fluid" href="{% url 'home' %}" ><img class="img-fluid" src="{% static 'img/navbar/logo.png' %}" id="Logo" /></p>
    </h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item mx-sm-1">
          <a class="nav-link {% if request.path == customer_home_page %}active{% endif %}" href="{{customer_home_page}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item mx-sm-1">
          <a class="nav-link {% if request.path == customer_service_page %}active{% endif %}" href="{{customer_service_page}}">Services</a>
        </li>
        <li class="nav-item mx-sm-1">
          {% if not user.is_authenticated or user.is_customer %}
          <a class="nav-link {% if request.path == business_list_page %}active{% endif %}" href="{{business_list_page}}">Business</a>
          {% else %}
            <a class="nav-link" href="{% if request.user.is_business %}{% url 'adminbusiness:business-dash' %}{% elif request.user.is_worker %}{% url 'worker:worker-dashboard' %}{% elif request.user.is_staff %}{% url 'admindashboard:my-admin-dashboard' %}{% endif %}">Dashboard</a>
          {% endif %}
        </li>
        <li class="nav-item mx-sm-1">
          <a class="nav-link {% if request.path == about_us_page %}active{% endif %}" href="{{about_us_page}}">About Us</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      {% if user.is_customer %}
      <ul class="nav navbar-nav navbar-right mt-4 me-4">
      {% show_notifications %}    
      </ul>
      {% endif %}  
      {% endif %}  
      <div class="mt-3 me-4" id="UDA">
        {% if user.is_authenticated %}
          {% if request.user.is_customer %}
          <img class="img-fluid rounded-circle mb-2 me-1" id="Profile" src="{{request.user.customer.image.url}}" onclick="open_dropdown()"/>
          {% elif request.user.is_business %}
          <img class="img-fluid rounded-circle mb-2 me-1" id="Profile" src="{{request.user.business.logo.url}}" onclick="open_dropdown()"/>
          {% elif request.user.is_worker %}
          <img class="img-fluid rounded-circle mb-2 me-1" id="Profile" src="{{request.user.worker.picture.url}}" onclick="open_dropdown()"/>
          {% endif %} 
        {% else %}
        <a class="btn btn-outline-success  " href="{{login_page}}" role="button"  aria-expanded="false">
          Get started
        </a>
        {% endif %}
        <span class=" dropdown-opener" onclick="open_dropdown()"></span>
        <div class="dropdown-content">
          {% if user.is_authenticated %}
            <a class="mb-1 flex {% if request.user.is_staff %} disabled{% endif %}{{ active_profile }}" 
            href="{% if request.user.is_customer %}{% url 'customer:customerprofile' %}
            {% elif request.user.is_business %}{% url 'adminbusiness:edit-business-profile-dash' %}
            {% elif request.user.is_worker %}{% url 'worker:worker-dashboard' %}{% endif %}" id="Username" >
            {% if request.user.is_customer %}{{request.user.customer.name}}
            {% elif request.user.is_business %}{{request.user.business.name}}
            {% elif request.user.is_worker %}{{request.user.worker.name}}{% else %}
            {{request.user.username}}{% endif %}</p> 
            <li class="dropdown-divider"></li>
            <a class="mb-1 lgo" href="{% url 'logout' %}">Log out</a>
          {% else %}
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</div>

templates/components/display_messages.html
<div aria-live="polite" aria-atomic="true" class="position-relative">
  <!-- Position it: -->
  <!-- - `.toast-container` for spacing between toasts -->
  <!-- - `.position-absolute`, `top-0` & `end-0` to position the toasts in the upper right corner -->
  <!-- - `.p-3` to prevent the toasts from sticking to the edge of the container  -->
  <div class="toast-container position-fixed bottom-0 end-0 me-2 mb-2">

{% for message in messages %}
    <!-- Then put toasts within -->
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="9000">
      <div class="toast-header">
      <svg class="bd-placeholder-img rounded me-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#007aff"></rect></svg>
      {% comment %} <i class="fas fa-info-circle me-1"></i> {% endcomment %}
        <strong class="me-auto">Alert</strong>
        <small class="text-muted">just now</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
       {{message|safe}}
      </div>
    </div>
{% endfor %}
  </div>
</div>

templates/components/navbar_notification.html
{% load static %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true"
        aria-expanded="false"><i class="fas fa-bell fa-lg position-relative">
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-info"
                style="font-size:0.7rem;">
                {{notifications.count}} <span class="visually-hidden">unread messages</span></span>
        </i></a>
    <ul class="dropdown-menu notify-drop pull-right">
        <div class="notify-drop-title">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">New Notifications(<b>{{notifications.count}}</b>)</div>
            </div>
        </div>
        <!-- end notify title -->
        <!-- notify content -->
        <div class="drop-content">
            {% if notifications %}
            {% for notification in notifications %}
            <a href="{% url 'customer:hire-notification-api' notification.pk %}">
                <div class="notifications-item">
                    {% if notification.from_user.business.logo %}
                    <img src="{{object.from_user.business.logo.url}}">
                    {% else %}
                    <img src="{% static 'business/images/profile/building_company.png' %}">
                    {% endif %}
                    <div class="text">
                        <h4>{{notification.title}}</h4>
                        <p><b class="text-secondary">{{notification.from_user.business.name}}</b>
                            {{notification.message}}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
            {% else %}
            <p class="text-center">No Unread Notifications</p>
            {% endif %}
        </div>
        <div class="notify-drop-footer text-center">
            <a href="{% url 'customer:customer-all-notification-page' %}"><i class="fa fa-eye"></i> View All</a>
        </div>
    </ul>
</li>