admindashboard/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # <<====================Dashboard====================>>
    path('dashboard', views.dashboard, name='my-admin-dashboard'),

    # <<====================Customer Registration====================>>
    path('customer-registration', views.customer_registration,
         name='customer-registration'),

    # <<====================Business Registration====================>>
    path('business-registration', views.business_registration,
         name='business-registration'),

    # <<====================Administrator Registration====================>>
    path('staff-registration', views.administrator_registration,
         name="staff-registration"),

    # <<====================Service====================>>
    path('service', views.service, name='service-list'),
    path('delete-service/<int:service_id>',
         views.service_delete, name='service-delete'),
    path('update-service/<int:service_id>',
         views.service_update, name='service-update'),

    # <<====================Business====================>>
    path('business', views.business, name='show-all-business'),
    path('business_active/<int:business_id>',
         views.business_active, name='make-business-active'),
    path('business-inactive/<int:business_id>',
         views.business_inactive, name='make-business-inactive'),
    path('business-verified/<int:business_id>',
         views.business_verified, name='verify-business'),
    path('business-not-verified/<int:business_id>',
         views.business_not_verified, name='unverify-business'),
    path('view-business/<int:business_id>',
         views.business_view, name="view-business"),
    path('change-hire-status1/<int:business_id>/<int:hire_id>',
         views.change_hire_status1, name='change-hire-status'),

    # <<====================Customer====================>>
    path('customer', views.customer, name="my-admin-customer-list-view"),
    path('customer-active/<int:customer_id>',
         views.customer_active, name='make-customer-active'),
    path('customer-inactive/<int:customer_id>',
         views.customer_inactive, name='make-customer-inactive'),
    path('view-customer/<int:customer_id>',
         views.customer_view, name="view-customer"),
    path('change-hire-status2/<int:customer_id>/<int:hire_id>',
         views.change_hire_status2, name='change-hire-status-2'),

     # <<====================Customer====================>>
     path('report', views.reportUser, name="report-user"),
    path('change_reportUSer_status/<int:reportUser_id>',
         views.change_reportUSer_status, name='change-reportUSer-status'),
]

app_name = 'admindashboard'

business/urls.py
# External Import
from django.urls import path
from .import views
# Internal Import
from .views import(
    BusinessListPageView,
    BusinessReportingView,
)


urlpatterns = [
    path('business/', BusinessListPageView.as_view(), name='business-list-page'),
    path('business-profile/<str:slug>/',
         views.BusinessProfileView.as_view(), name='business-profile'),
    path('api/report-business/', BusinessReportingView.as_view(),
         name='user-report-business')
]

app_name = 'business'

customer/urls.py
# External Import
from django.urls import path
from customer import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
#from .views import PasswordUpdateView


# Internal Import

urlpatterns = [
    path('profile/', views.profileupdate, name="customerprofile"),
    path('change-password/', views.change_password, name='change_password'),
    path('hirings/', views.CustomerHiringPageView.as_view(),
         name="customer-hiring-page"),
    path('hirings/delete/<pk>/', views.CustomerHiringDeleteView.as_view(),
         name='customer-hiring-delete-view'),
    path('bookmarks/', views.CustomerBusinessBookmarkListView.as_view(),
         name="customer-bookmark-page"),
    path('bookmarks/delete/<pk>/', views.CustomerBookmarkDeleteView.as_view(),
         name='customer-bookmark-delete-view'),
    path('bookmarks/<str:slug>/add-bookmark/',
         views.business_bookmark_toggle_for_customer, name='customer-bookmark-toggle'),
    path('api/notification/<int:notification_pk>',
         views.HireNotificationView.as_view(), name='hire-notification-api'),
    path('notifications/', views.AllNotificationPageView.as_view(),
         name="customer-all-notification-page"),
    path('notification/<int:id>/toggle-notification-status/',
         views.notification_seen_toggle_for_customer, name='customer-notification-toggle'),


]

# App Name
app_name = 'customer'

hiring/urls.py
# External Import
from hiring.views import CreateHireView
from django.urls import path

urlpatterns = [
    path('hire/', CreateHireView.as_view(), name='hire-business-service')
]

app_name = 'hiring'

service/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Service, name='customer-services'),
]

admindashboard/models.py
from django.db import models

# Create your models here.

hiring/models.py
from django.db import models
from business.models import *
from customer.models import *
from worker.models import *


class Hiring(models.Model):
    PENDING = 'PE'
    ACCEPTED = 'AC'
    REJECTED = 'RE'
    CANCEL = 'CA'
    COMPLETED = 'CO'
    LATE = 'LA'
    HIRE_STATUS = [
        (PENDING, 'Pending'),
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
        (CANCEL, 'Cancel'),
        (COMPLETED, 'Completed'),
        (LATE, 'Late'),
    ]

    business_service = models.ForeignKey(
        Business_Service, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    worker = models.ForeignKey(
        Worker, on_delete=models.CASCADE, null=True, blank=True)
    date_time = models.DateTimeField(auto_now_add=True)
    customer_message = models.TextField(null=True)
    business_message = models.TextField(null=True)
    status = models.CharField(
        max_length=20, choices=HIRE_STATUS, default=PENDING)

    def __str__(self):
        name = str(self.business_service) + "-->" + str(self.customer)
        return name

business/forms.py
# External Import
from django import forms

# Internal Import
from review.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'
        exclude = ['customer', 'business', 'is_active']

customer/forms.py
# External Improt
from django.forms.widgets import Widget
from customer.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django import forms
from django.forms import ModelForm
from .models import Customer


# Internal Import
from customer.models import Customer, PROVINCE_CHOICES
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
     model=Customer
     fields= ['name','phone','province','city','street_address','image']

 

admindashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
import random
import string
from django.contrib.sites.shortcuts import get_current_site

from django.contrib.auth.decorators import login_required
from accounts.auth import *

from django.contrib.auth.models import User
from django.urls.base import reverse_lazy
from business.models import *
from gallery.models import *
from worker.models import *
from customer.models import *
from service.models import *
from hiring.models import *
from review.models import *
from notification.models import *
from bookmark.models import *
from reportuser.models import *

from .forms import *
from .filters import *
from accounts import utils


# <<====================Dashboard====================>>
@login_required
@admin_only
def dashboard(request):
    user = User.objects.all().count()
    admin = User.objects.filter(is_staff=True).all().count()
    service = Services.objects.all().count()
    business = Business.objects.foradmin().count()
    gallery = Gallery.objects.all().count()
    business_service = Business_Service.objects.all().count()
    worker = Worker.objects.all().count()
    customer = Customer.objects.all().count()
    hiring = Hiring.objects.all().count()
    review = Review.objects.all().count()
    notification = Notification.objects.all().count()
    bookmark = Bookmark.objects.all().count()
    report = ReportUser.objects.all().count()

    dictionary = {
        'user': user,
        'admin': admin,
        'service': service,
        'business': business,
        'gallery': gallery,
        'worker': worker,
        'business_service': business_service,
        'customer': customer,
        'hiring': hiring,
        'review': review,
        'notification': notification,
        'bookmark': bookmark,
        'report':report,
        'dashboard': 'selected'
    }
    return render(request, 'admindashboard/dashboard.html', dictionary)

# <<====================Customer Registration====================>>


@login_required
@admin_only
def customer_registration(request):
    u_form = CustomerCreationForm(request.POST or None)
    if request.method == 'POST':
        if u_form.is_valid():
            letters = string.ascii_lowercase
            password = ''.join(random.choice(letters) for i in range(12))
            user = u_form.save(commit=False)
            user.is_customer = True
            user.is_active = True
            user.set_password(password)
            user.save()
            Customer.objects.create(user=user)
            current_site = get_current_site(request)
            login = reverse_lazy('login')
            login_url = f'http://www.{current_site}{login}'
            subject = "Account Created At GharDailo"
            message = f'Your Account has been created for GharDailo.\nYour Username: {user.username}\nYour Password: {password}\nDon\'t Share the details with other\nTo Login Visit: {login_url}'
            utils.send_email_to_user(subject, message, user)
            messages.success(
                request, f'{user.username} Customer user has been created')
            return redirect('admindashboard:my-admin-dashboard')
    context = {
        'u_form': u_form,
        'dashboard': 'selected'
    }
    return render(request, 'admindashboard/Customer_Registration.html', context)


# <<====================Business Registration====================>>
@login_required
@admin_only
def business_registration(request):
    u_form = BusinessCreationForm(request.POST or None)
    if request.method == 'POST':
        if u_form.is_valid():
            letters = string.ascii_lowercase
            password = ''.join(random.choice(letters) for i in range(12))
            user = u_form.save(commit=False)
            user.is_business = True
            user.is_active = True
            user.set_password(password)
            user.save()
            business_name = u_form.cleaned_data.get('business_name')
            Business.objects.create(user=user, name=business_name)
            current_site = get_current_site(request)
            login = reverse_lazy('login')
            login_url = f'http://www.{current_site}{login}'
            subject = "Account Created At GharDailo"
            message = f'Your Account has been created for GharDailo.\nYour Username: {user.username}\nYour Password: {password}\nDon\'t Share the details with other\nTo Login Visit: {login_url}'
            utils.send_email_to_user(subject, message, user)
            messages.success(
                request, f'{user.username} Business user has been created')
            return redirect('admindashboard:my-admin-dashboard')
    context = {
        'u_form': u_form,
        'dashboard': 'selected'
    }
    return render(request, 'admindashboard/Business_Registration.html', context)


# <<====================Administration Registration====================>>
@login_required
@admin_only
def administrator_registration(request):
    u_form = StaffUserCreationForm(request.POST or None)
    if request.method == 'POST':
        if u_form.is_valid():
            password = u_form.cleaned_data['password']
            user = u_form.save(commit=False)
            user.is_staff = True
            user.is_admin = True
            user.is_active = True
            user.set_password(password)
            user.save()
            messages.success(
                request, f'{user.username} staff user has been created')
            return redirect('admindashboard:my-admin-dashboard')
    context = {
        'u_form': u_form,
        'dashboard': 'selected'
    }
    return render(request, 'admindashboard/Administrator_Registration.html', context)


# <<====================Service====================>>
@login_required
@admin_only
def service(request):
    service = Services.objects.all()
    service_filter = ServicesFilter(request.GET, queryset=service)
    service_final = service_filter.qs

    form = ServicesForm
    if request.method == "POST":
        form = ServicesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'New service has been added to GharDailo.')
            return redirect('admindashboard:service-list')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Failed to add service, please try again!!!')
            return render(request, 'admindashboard/servie.html', {'services': service_final, 'service_filter': service_filter, 'form': form, 'BTM': 'Add', 'service': 'selected'})
    dictionary = {
        'services': service_final,
        'service_filter': service_filter,
        'form': form,
        'BTM': 'Add',
        'service': 'selected'
    }

    return render(request, 'admindashboard/service.html', dictionary)


@login_required
@admin_only
def service_delete(request, service_id):
    service = Services.objects.get(id=service_id)
    service_name = service.name
    service.delete()
    messages.add_message(request, messages.SUCCESS, "'" +
                         service_name + "'"+' service has been removed.')
    return redirect('admindashboard:service-list')


@login_required
@admin_only
def service_update(request, service_id):
    service = Services.objects.all()
    service_filter = ServicesFilter(request.GET, queryset=service)
    service_final = service_filter.qs

    particular_service = Services.objects.get(id=service_id)
    form = ServicesForm(instance=particular_service)
    if request.method == "POST":
        form = ServicesForm(request.POST, instance=particular_service)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Service has been updated.')
            return redirect('admindashboard:service-list')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Failed to update service, please try again!!!')
            return render(request, 'admindashboard/servie.html', {'services': service_final, 'service_filter': service_filter, 'form': form, 'BTM': 'Update', 'service': 'selected'})
    dictionary = {'services': service_final, 'service_filter': service_filter,
                  'form': form, 'BTM': 'Update', 'service': 'selected'}
    return render(request, 'admindashboard/service.html', dictionary)


# <<====================Business====================>>
@login_required
@admin_only
def business(request):
    business = Business.objects.foradmin()
    business_filter = BusinessFilter(request.GET, queryset=business)
    business_final = business_filter.qs

    dictionary = {
        'businesses': business_final,
        'business_filter': business_filter,
        'business': 'selected'
    }
    return render(request, 'admindashboard/business.html', dictionary)


@login_required
@admin_only
def business_active(request, business_id):
    particular_business = Business.objects.get(id=business_id)
    particular_business.is_active = True
    particular_business.save()
    return redirect("admindashboard:show-all-business")


@login_required
@admin_only
def business_inactive(request, business_id):
    particular_business = Business.objects.get(id=business_id)
    particular_business.is_active = False
    particular_business.save()
    return redirect("admindashboard:show-all-business")


@login_required
@admin_only
def business_verified(request, business_id):
    particular_business = Business.objects.get(id=business_id)
    particular_business.is_verified = True
    particular_business.save()
    return redirect("admindashboard:show-all-business")


@login_required
@admin_only
def business_not_verified(request, business_id):
    particular_business = Business.objects.get(id=business_id)
    particular_business.is_verified = False
    particular_business.save()
    return redirect("admindashboard:show-all-business")

service/views.py
from django.shortcuts import render

# Internal Improt
from .filter import *
from .models import Services

# Create your views here.
def Service(request):
    service = Services.objects.filter(is_active=True)
    service_filter = ServicesFilter(request.GET, queryset=service)
    service_final = service_filter.qs
    context = {
        'services': service_final,
        'service_filter': service_filter,
     
    }
    return render(request, 'links/services.html', context)

admindashboard/templates/admindashboard/business.html
{% extends 'base/admin_layout.html' %}
{% load static %}
{% block title %}
    Admin Business
{% endblock %}
{% block additional_head %}
    <link href="{% static 'css/admin_business.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block main_content %}   
<div class="search_box mt-3">
    <form class="form" method="GET">
        {{business_filter.form.name}}
        <button class="btn" type="submit"><span class="fas fa-search"></span></button>
    </form>
</div>
<div class="table-responsive mt-3">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">User</th>
                <th scope="col">Name</th>
                <th scope="col">Logo</th>
                <th scope="col">District</th>
                <th scope="col">Province</th>
                <th scope="col">Phone</th>
                <th scope="col">Active</th>
                <th scope="col">Modify Activeness</th>
                <th scope="col">Verified</th>
                <th scope="col">Modify Verification</th>
                <th scope="col">View</th>
            </tr>
        </thead>
        <tbody>
            {% for i in businesses %}
                <tr>
                    <td scope="row" class="Numbering"></td>
                    <td>{{i.user.username}}</td>
                    <td>{{i.name}}</td>
                    <td>
                        {% if i.logo %}
                            <img class="img-fluid rounded-circle" src="{{i.logo.url}}" />
                        {% else %}
                            No logo
                        {% endif %}
                    </td>
                    <td>{{i.district}}</td>
                    <td>{{i.province}}</td>
                    <td>{{i.phone}}</td>
                    <td>                        
                        {% if i.is_active == True %}
                        <span class="fas fa-check-circle"></span>
                        {% else %}
                        <span class="fas fa-times-circle"></span>
                        {% endif %}
                    </td>
                    <td>
                        {% if i.is_active == False %}
                        <a href="{% url 'admindashboard:make-business-active' i.id %}" class="active" onclick="return confirm('Do you want activate this business?')"><span class="fas fa-check-circle"></span></a>
                        {% else %}
                        <a href="{% url 'admindashboard:make-business-inactive' i.id %}" class="inactive" onclick="return confirm('Do you want inactivate this business?')"><span class="fas fa-times-circle"></span></a>
                        {% endif %}
                    </td>
                    <td>                        
                        {% if i.is_verified == True %}
                        <span class="fas fa-check-circle"></span>
                        {% else %}
                        <span class="fas fa-times-circle"></span>
                        {% endif %}
                    </td>
                    <td>
                        {% if i.is_verified == False %}
                        <a href="{% url 'admindashboard:verify-business' i.id %}" class="verified" onclick="return confirm('Do you want to make verified this business?')"><span class="fas fa-check-circle"></span></a>
                        {% else %}
                        <a href="{% url 'admindashboard:unverify-business' i.id %}" class="not_verified" onclick="return confirm('Do you want to make unverified of this business?')"><span class="fas fa-times-circle"></span></a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'admindashboard:view-business' i.id %}" class="edit"><span class="fas fa-eye me-3 mb-3 edit"></span></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div> 
{% endblock %}

{% block additional_body %}
<script>
    document.getElementsByTagName("input")[0].placeholder="Search Businesses"
</script>
<script src="{% static 'js/numbering.js' %}"></script>
{% endblock %}

admindashboard/templates/admindashboard/customer.html
{% extends 'base/admin_layout.html' %}
{% load static %}
{% block title %}
    Admin Dashboard
{% endblock %}
{% block additional_head %}
<link href="{% static 'css/admin_customer.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block main_content %}
<div class="container-fluid search_box mt-3">
    <form class="form" method="GET">
        {{customer_filter.form.name}}
        <button class="btn" type="submit"><span class="fas fa-search"></span></button>
    </form>
</div>
<div class="table-responsive mt-3 me-2">
    <table class="table table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">User</th>
                <th scope="col">Name</th>
                <th scope="col">Profile</th>
                <th scope="col">Phone</th>
                <th scope="col">Province</th>
                <th scope="col">City</th>
                <th scope="col">Street</th>
                <th scope="col">Active</th>
                <th scope="col">Modify Activeness</th>
                <th scope="col">View</th>
            </tr>
        </thead>
        <tbody>
            {% for i in customers %}
                <tr>
                    <td scope="row" class="Numbering"></td>
                    <td>{{i.user.username}}</td>
                    <td>{{i.name}}</td>
                    <td>                         
                        {% if i.image.url != "/media/static/Image/default.jpg" %}
                            <img class="img-fluid rounded-circle" src="{{i.image.url}}" alt="" />
                        {% else %}
                            <img class="img-fluid rounded-circle" src="/{{i.image}}" alt="" />
                        {% endif %}
                    </td>
                    <td>{{i.phone}}</td>
                    <td>{{i.province}}</td>
                    <td>{{i.city}}</td>
                    <td>{{i.street_address}}</td>
                    <td>                        
                        {% if i.is_active == True %}
                        <span class="fas fa-check-circle"></span>
                        {% else %}
                        <span class="fas fa-times-circle"></span>
                        {% endif %}
                    </td>
                    <td>
                        {% if i.is_active == False %}
                        <a href="{% url 'admindashboard:make-customer-active' i.id %}" class="active" onclick="return confirm('Do you want activate this customer?')"><span class="fas fa-check-circle"></span></a>
                        {% else %}
                        <a href="{% url 'admindashboard:make-customer-inactive' i.id %}" class="inactive" onclick="return confirm('Do you want inactivate this customer?')"><span class="fas fa-times-circle"></span></a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'admindashboard:view-customer' i.id %}"><span class="fas fa-eye me-3 mb-3 edit"></span></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div> 
{% endblock %}

{% block additional_body %}
<script>
    document.getElementsByTagName("input")[0].placeholder="Search Customers"
</script>
<script src="{% static 'js/numbering.js' %}"></script>
{% endblock %}

admindashboard/templates/admindashboard/dashboard.html
{% extends 'base/admin_layout.html' %}
{% load static %}
{% block title %}
    Admin Dashboard
{% endblock %}
{% block additional_head %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block main_content %}  
<div class="container-fluid mt-3">
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="success_message alert alert-success mb-3 text-center" role="alert"><span class="fas fa-check-circle me-2"></span>{{message}}</div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="error_message alert alert-danger mb-3 text-center" role="alert"><span class="fas fa-exclamation-triangle me-2"></span>{{message}}</div>
        {% endif %}
    {% endfor %}       
</div>    
<div class="container-fluid Registration mt-3">
  <div class="Customer">
    <a href="{% url 'admindashboard:customer-registration' %}"><span class="fas fa-user-friends logo me-1"></span><span class="fas fa-plus plus"></span></a>    
    <a href="{% url 'admindashboard:customer-registration' %}"><span>Add new Customer</span></a>
  </div>
  <div class="Business">
    <a href="{% url 'admindashboard:business-registration' %}"><span class="fas fa-user-tie logo me-1"></span><span class="fas fa-plus plus"></span></a>    
    <a href="{% url 'admindashboard:business-registration' %}"><span>Add new Business</span></a>
  </div>
  <div class="Admin">
    <a href="{% url 'admindashboard:staff-registration' %}"><span class="fas fa-user-secret logo me-1"></span><span class="fas fa-plus plus"></span></a>    
    <a href="{% url 'admindashboard:staff-registration' %}"><span>Add new Administrator</span></a>
  </div>
</div>
<div class="container-fluid mt-5 ProgressBars" id="Items">
  <div class="Bar">
    <div class="text service"><span class="fas fa-tools me-2 logo"></span>Services</div>
    <div class="circle">
      <a href="{% url 'admindashboard:service-list' %}">
        <div class="bar"></div>
        <div class="box"><span id="bs">{{service}}</span></div>
      </a> 
    </div>
  </div>
  <div class="Bar">
    <div class="text"><span class="fas fa-users me-2 logo"></span>Users</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bu">{{user}}</span></div>
    </div>
  </div>       
  <div class="Bar">
    <div class="text"><span class="fas fa-user-secret me-2 logo"></span>administrators</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bc">{{admin}}</span></div>
    </div>
  </div>  
  <div class="Bar">
    <div class="text"><span class="fas fa-user-friends me-2 logo"></span>Customers</div>
    <div class="circle">
      <a href="{% url 'admindashboard:my-admin-customer-list-view' %}">
        <div class="bar"></div>
        <div class="box"><span id="bc">{{customer}}</span></div>
      </a>
    </div>
  </div>  
  <div class="Bar">
    <div class="text"><span class="fas fa-user-tie me-2 logo"></span>Businesses</div>
    <div class="circle">
      <a href="{% url 'admindashboard:show-all-business' %}">
        <div class="bar"></div>
        <div class="box"><span id="bb">{{business}}</span></div>
      </a>
    </div>
  </div>   
  <div class="Bar">
    <div class="text"><span class="fas fa-user me-2 logo"></span>Workers</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bw">{{worker}}</span></div>
    </div>
  </div>    
  <div class="Bar">
    <div class="text"><span class="fas fa-images me-2 logo"></span>Pictures</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bg">{{gallery}}</span></div>
    </div>
  </div>   
  <div class="Bar">
    <div class="text"><span class="fas fa-hands-helping me-2 logo"></span>Hires</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bh">{{hiring}}</span></div>
    </div>
  </div>  
  <div class="Bar">
    <div class="text"><span class="fas fa-search-plus me-2 logo"></span>Reviews</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="br">{{review}}</span></div>
    </div>
  </div> 
  <div class="Bar">
    <div class="text"><span class="fas fa-bell me-2 logo"></span>Notifications</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bn">{{notification}}</span></div>
    </div>
  </div>       
  <div class="Bar">
    <div class="text"><span class="fas fa-bookmark me-2 logo"></span>Bookmarks</div>
    <div class="circle">
      <div class="bar"></div>
      <div class="box"><span id="bn">{{bookmark}}</span></div>
    </div>
  </div>         
  <div class="Bar">
    <div class="text"><span class="fas fa-exclamation-circle me-2 logo"></span>Reports</div>
    <div class="circle">
      <a href="{% url 'admindashboard:report-user' %}">
        <div class="bar"></div>
        <div class="box"><span id="bn">{{report}}</span></div>
      </a>
    </div>
  </div>   
</div> 
{% endblock %}

{% block additional_body %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-circle-progress/1.2.2/circle-progress.min.js" integrity="sha512-6kvhZ/39gRVLmoM/6JxbbJVTYzL/gnbDVsHACLx/31IREU4l3sI7yeO0d4gw8xU5Mpmm/17LMaDHOCf+TvuC2Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> 
  <script src="{% static 'js/dashboard.js' %}"></script>
{% endblock %}